export const DEFAULT_USER_ID = "local-user";

export const DEFAULT_EXERCISES = [
  // ── Traditional lifting (WEIGHT_REPS) ──
  {
    name: "Incline Dumbbell Press",
    slug: "incline-dumbbell-press",
    category: "CHEST",
    movementPattern: "PUSH",
    equipment: "DUMBBELL",
    measurementType: "WEIGHT_REPS",
    primaryMuscle: "Upper Chest",
    secondaryMuscles: "Front Delts, Triceps",
    incrementStep: 2.5,
    repTargetMin: 6,
    repTargetMax: 10,
    targetRirMin: 0,
    targetRirMax: 2,
    durationTargetSeconds: null,
    distanceTargetKm: null,
    isCustom: false,
  },
  {
    name: "Romanian Deadlift",
    slug: "romanian-deadlift",
    category: "LEGS",
    movementPattern: "HINGE",
    equipment: "BARBELL",
    measurementType: "WEIGHT_REPS",
    primaryMuscle: "Hamstrings",
    secondaryMuscles: "Glutes, Lower Back",
    incrementStep: 5,
    repTargetMin: 6,
    repTargetMax: 10,
    targetRirMin: 0,
    targetRirMax: 2,
    durationTargetSeconds: null,
    distanceTargetKm: null,
    isCustom: false,
  },
  {
    name: "Lat Pulldown",
    slug: "lat-pulldown",
    category: "BACK",
    movementPattern: "PULL",
    equipment: "CABLE",
    measurementType: "WEIGHT_REPS",
    primaryMuscle: "Lats",
    secondaryMuscles: "Biceps, Upper Back",
    incrementStep: 2.5,
    repTargetMin: 8,
    repTargetMax: 12,
    targetRirMin: 0,
    targetRirMax: 2,
    durationTargetSeconds: null,
    distanceTargetKm: null,
    isCustom: false,
  },
  // ── Bodyweight / Reps only (REPS_ONLY) ──
  {
    name: "Push-Up",
    slug: "push-up",
    category: "CHEST",
    movementPattern: "PUSH",
    equipment: "BODYWEIGHT",
    measurementType: "REPS_ONLY",
    primaryMuscle: "Chest",
    secondaryMuscles: "Triceps, Front Delts",
    incrementStep: 1,
    repTargetMin: 8,
    repTargetMax: 15,
    targetRirMin: 0,
    targetRirMax: 2,
    durationTargetSeconds: null,
    distanceTargetKm: null,
    isCustom: false,
  },
  {
    name: "Pull-Up",
    slug: "pull-up",
    category: "BACK",
    movementPattern: "PULL",
    equipment: "BODYWEIGHT",
    measurementType: "REPS_ONLY",
    primaryMuscle: "Lats",
    secondaryMuscles: "Biceps, Upper Back",
    incrementStep: 1,
    repTargetMin: 5,
    repTargetMax: 10,
    targetRirMin: 0,
    targetRirMax: 2,
    durationTargetSeconds: null,
    distanceTargetKm: null,
    isCustom: false,
  },
  // ── Time-based (TIME) ──
  {
    name: "Dead Hang",
    slug: "dead-hang",
    category: "BACK",
    movementPattern: "CARRY",
    equipment: "BODYWEIGHT",
    measurementType: "TIME",
    primaryMuscle: "Grip, Lats",
    secondaryMuscles: "Forearms, Shoulders",
    incrementStep: 0,
    repTargetMin: 0,
    repTargetMax: 0,
    targetRirMin: 0,
    targetRirMax: 0,
    durationTargetSeconds: 30,
    distanceTargetKm: null,
    isCustom: false,
  },
  {
    name: "Plank",
    slug: "plank",
    category: "CORE",
    movementPattern: "CARRY",
    equipment: "BODYWEIGHT",
    measurementType: "TIME",
    primaryMuscle: "Core",
    secondaryMuscles: "Glutes, Shoulders",
    incrementStep: 0,
    repTargetMin: 0,
    repTargetMax: 0,
    targetRirMin: 0,
    targetRirMax: 0,
    durationTargetSeconds: 60,
    distanceTargetKm: null,
    isCustom: false,
  },
  // ── Cardio (DISTANCE_TIME) ──
  {
    name: "Running",
    slug: "running",
    category: "CARDIO",
    movementPattern: "OTHER",
    equipment: "OTHER",
    measurementType: "DISTANCE_TIME",
    primaryMuscle: "Legs, Cardiovascular",
    secondaryMuscles: "Core",
    incrementStep: 0,
    repTargetMin: 0,
    repTargetMax: 0,
    targetRirMin: 0,
    targetRirMax: 0,
    durationTargetSeconds: null,
    distanceTargetKm: 5,
    isCustom: false,
  },
] as const;
